name: document_scanner_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_tesseract_ocr: ^0.4.30
  html: ^0.15.6
  pdf: ^3.11.3
  flutter_pdfview: ^1.3.2
  permission_handler: ^12.0.1
  google_mlkit_text_recognition: ^0.15.0
  text_recognition_pipeline:
    path: ../native_text_recognition_pipeline/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tesseract/
    - assets/tesseract/tessdata/
